language: node_js
node_js: "8"
script: 
  - npm run build
deploy:
  provider: github_pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh_pages
  local_dir: ./dist
  on:
    branch: master